### ISSUE TITLE
Product didn't fetch properly. 

### ISSUE THREAD

**Issue by wolfofwolverhampton** [anjinashahi/Lugaa#7]

**Comment by anjinashahi** [comment]
<?php 
                $result = mysqli_query($conn, "SELECT * FROM test_newarrival ORDER BY id DESC");
                while ($row = mysqli_fetch_assoc($result)) :?>
                <div class="product">
                <img src="img/<?php echo $row['image']; ?>" alt="">
                <div class="details">
                        <h3><?php echo $row["name"]; ?></h3>
                        <p><?php echo $row["act_price"]; ?></p>
                        
                        <button class="buy-button">Buy Now</button>
                    </div>
                </div>
                <?php endwhile; ?> 
                
                
                
 after reviewing the code your database didn't match with your code please check i properly
